INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Chicago Bears","New England Patriots","5","-110","open-line");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New England Patriots","Chicago Bears","-5","-110","open-line");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Chicago Bears","New England Patriots","8","-110","vi-consensus");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New England Patriots","Chicago Bears","-8","-112","vi-consensus");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Chicago Bears","New England Patriots","7.5","-105","fanduel");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New England Patriots","Chicago Bears","-7.5","-115","fanduel");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Chicago Bears","New England Patriots","8","-110","playmgm");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New England Patriots","Chicago Bears","-8","-110","playmgm");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Chicago Bears","New England Patriots","8","-110","caesars-sportsbook");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New England Patriots","Chicago Bears","-8","-110","caesars-sportsbook");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Chicago Bears","New England Patriots","8","-110","wynnbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New England Patriots","Chicago Bears","-8","-110","wynnbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Chicago Bears","New England Patriots","8","-109","betrivers");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New England Patriots","Chicago Bears","-8","-112","betrivers");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Chicago Bears","New England Patriots","9","-108","pointsbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New England Patriots","Chicago Bears","-9","-108","pointsbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Chicago Bears","New England Patriots","8","-110","draftkings");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New England Patriots","Chicago Bears","-8","-110","draftkings");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Chicago Bears","New England Patriots","8.5","-110","sports-illustrated");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New England Patriots","Chicago Bears","-8.5","-110","sports-illustrated");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Chicago Bears","New England Patriots","8","-109","sugarhouse");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New England Patriots","Chicago Bears","-8","-112","sugarhouse");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Chicago Bears","New England Patriots","8","-109","unibet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New England Patriots","Chicago Bears","-8","-112","unibet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Pittsburgh Steelers","Miami Dolphins","3.5","-110","open-line");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Miami Dolphins","Pittsburgh Steelers","-3.5","-110","open-line");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Pittsburgh Steelers","Miami Dolphins","7.5","-115","vi-consensus");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Miami Dolphins","Pittsburgh Steelers","-7.5","-105","vi-consensus");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Pittsburgh Steelers","Miami Dolphins","7","-105","fanduel");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Miami Dolphins","Pittsburgh Steelers","-7","-115","fanduel");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Pittsburgh Steelers","Miami Dolphins","7.5","-115","playmgm");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Miami Dolphins","Pittsburgh Steelers","-7.5","-105","playmgm");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Pittsburgh Steelers","Miami Dolphins","7","-105","caesars-sportsbook");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Miami Dolphins","Pittsburgh Steelers","-7","-115","caesars-sportsbook");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Pittsburgh Steelers","Miami Dolphins","7","+100","wynnbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Miami Dolphins","Pittsburgh Steelers","-7","-120","wynnbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Pittsburgh Steelers","Miami Dolphins","7.5","-115","betrivers");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Miami Dolphins","Pittsburgh Steelers","-7.5","-105","betrivers");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Pittsburgh Steelers","Miami Dolphins","7","+100","pointsbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Miami Dolphins","Pittsburgh Steelers","-7","-115","pointsbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Pittsburgh Steelers","Miami Dolphins","7","-110","draftkings");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Miami Dolphins","Pittsburgh Steelers","-7","-110","draftkings");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Pittsburgh Steelers","Miami Dolphins","9.5","-133","sports-illustrated");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Miami Dolphins","Pittsburgh Steelers","-9.5","+110","sports-illustrated");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Pittsburgh Steelers","Miami Dolphins","7.5","-115","sugarhouse");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Miami Dolphins","Pittsburgh Steelers","-7.5","-105","sugarhouse");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Pittsburgh Steelers","Miami Dolphins","7.5","-115","unibet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Miami Dolphins","Pittsburgh Steelers","-7.5","-105","unibet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Seattle Seahawks","Los Angeles Chargers","8.5","-110","open-line");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Los Angeles Chargers","Seattle Seahawks","-8.5","-110","open-line");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Seattle Seahawks","Los Angeles Chargers","5","-110","vi-consensus");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Los Angeles Chargers","Seattle Seahawks","-5","-110","vi-consensus");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Seattle Seahawks","Los Angeles Chargers","4.5","-105","fanduel");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Los Angeles Chargers","Seattle Seahawks","-4.5","-115","fanduel");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Seattle Seahawks","Los Angeles Chargers","4.5","-110","playmgm");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Los Angeles Chargers","Seattle Seahawks","-4.5","-110","playmgm");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Seattle Seahawks","Los Angeles Chargers","4.5","-110","caesars-sportsbook");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Los Angeles Chargers","Seattle Seahawks","-4.5","-110","caesars-sportsbook");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Seattle Seahawks","Los Angeles Chargers","5","-110","wynnbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Los Angeles Chargers","Seattle Seahawks","-5","-110","wynnbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Seattle Seahawks","Los Angeles Chargers","5","-110","betrivers");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Los Angeles Chargers","Seattle Seahawks","-5","-110","betrivers");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Seattle Seahawks","Los Angeles Chargers","4.5","-108","pointsbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Los Angeles Chargers","Seattle Seahawks","-4.5","-108","pointsbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Seattle Seahawks","Los Angeles Chargers","5","-110","draftkings");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Los Angeles Chargers","Seattle Seahawks","-5","-110","draftkings");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Seattle Seahawks","Los Angeles Chargers","4.5","-110","sports-illustrated");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Los Angeles Chargers","Seattle Seahawks","-4.5","-110","sports-illustrated");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Seattle Seahawks","Los Angeles Chargers","5","-110","sugarhouse");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Los Angeles Chargers","Seattle Seahawks","-5","-110","sugarhouse");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Seattle Seahawks","Los Angeles Chargers","5","-110","unibet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Los Angeles Chargers","Seattle Seahawks","-5","-110","unibet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Kansas City Chiefs","San Francisco 49ers","-1","-110","open-line");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","San Francisco 49ers","Kansas City Chiefs","1","-110","open-line");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Kansas City Chiefs","San Francisco 49ers","-1","-110","vi-consensus");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","San Francisco 49ers","Kansas City Chiefs","1","-110","vi-consensus");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Kansas City Chiefs","San Francisco 49ers","-1.5","-108","fanduel");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","San Francisco 49ers","Kansas City Chiefs","1.5","-112","fanduel");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Kansas City Chiefs","San Francisco 49ers","-1","-105","playmgm");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","San Francisco 49ers","Kansas City Chiefs","1","-115","playmgm");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Kansas City Chiefs","San Francisco 49ers","0","-110","caesars-sportsbook");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","San Francisco 49ers","Kansas City Chiefs","0","-110","caesars-sportsbook");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Kansas City Chiefs","San Francisco 49ers","-1","-110","wynnbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","San Francisco 49ers","Kansas City Chiefs","1","-110","wynnbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Kansas City Chiefs","San Francisco 49ers","-1","-109","betrivers");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","San Francisco 49ers","Kansas City Chiefs","1","-112","betrivers");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Kansas City Chiefs","San Francisco 49ers","-1","-108","pointsbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","San Francisco 49ers","Kansas City Chiefs","1","-108","pointsbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Kansas City Chiefs","San Francisco 49ers","-1","-105","draftkings");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","San Francisco 49ers","Kansas City Chiefs","1","-115","draftkings");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Kansas City Chiefs","San Francisco 49ers","1.5","-133","sports-illustrated");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","San Francisco 49ers","Kansas City Chiefs","-1.5","+110","sports-illustrated");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Kansas City Chiefs","San Francisco 49ers","-1","-109","sugarhouse");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","San Francisco 49ers","Kansas City Chiefs","1","-112","sugarhouse");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Kansas City Chiefs","San Francisco 49ers","-1","-109","unibet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","San Francisco 49ers","Kansas City Chiefs","1","-112","unibet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New York Jets","Denver Broncos","7.5","-110","open-line");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Denver Broncos","New York Jets","-7.5","-110","open-line");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New York Jets","Denver Broncos","-2","-112","vi-consensus");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Denver Broncos","New York Jets","2","-110","vi-consensus");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New York Jets","Denver Broncos","-2.5","-110","fanduel");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Denver Broncos","New York Jets","2.5","-110","fanduel");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New York Jets","Denver Broncos","-2.5","-110","playmgm");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Denver Broncos","New York Jets","2.5","-110","playmgm");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New York Jets","Denver Broncos","-2","-110","caesars-sportsbook");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Denver Broncos","New York Jets","2","-110","caesars-sportsbook");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New York Jets","Denver Broncos","-2","-110","wynnbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Denver Broncos","New York Jets","2","-110","wynnbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New York Jets","Denver Broncos","-2","-112","betrivers");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Denver Broncos","New York Jets","2","-109","betrivers");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New York Jets","Denver Broncos","-2","-110","pointsbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Denver Broncos","New York Jets","2","-105","pointsbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New York Jets","Denver Broncos","-2.5","-110","draftkings");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Denver Broncos","New York Jets","2.5","-110","draftkings");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New York Jets","Denver Broncos","-2.5","-110","sports-illustrated");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Denver Broncos","New York Jets","2.5","-110","sports-illustrated");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New York Jets","Denver Broncos","-2","-112","sugarhouse");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Denver Broncos","New York Jets","2","-109","sugarhouse");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New York Jets","Denver Broncos","-2","-112","unibet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Denver Broncos","New York Jets","2","-109","unibet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Houston Texans","Las Vegas Raiders","8","-110","open-line");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Las Vegas Raiders","Houston Texans","-8","-110","open-line");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Houston Texans","Las Vegas Raiders","7","-110","vi-consensus");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Las Vegas Raiders","Houston Texans","-7","-110","vi-consensus");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Houston Texans","Las Vegas Raiders","7","-110","fanduel");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Las Vegas Raiders","Houston Texans","-7","-110","fanduel");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Houston Texans","Las Vegas Raiders","7","-110","playmgm");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Las Vegas Raiders","Houston Texans","-7","-110","playmgm");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Houston Texans","Las Vegas Raiders","7","-110","caesars-sportsbook");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Las Vegas Raiders","Houston Texans","-7","-110","caesars-sportsbook");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Houston Texans","Las Vegas Raiders","7","-110","wynnbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Las Vegas Raiders","Houston Texans","-7","-110","wynnbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Houston Texans","Las Vegas Raiders","7","-110","betrivers");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Las Vegas Raiders","Houston Texans","-7","-110","betrivers");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Houston Texans","Las Vegas Raiders","7.5","-110","pointsbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Las Vegas Raiders","Houston Texans","-7.5","-105","pointsbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Houston Texans","Las Vegas Raiders","7","-110","draftkings");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Las Vegas Raiders","Houston Texans","-7","-110","draftkings");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Houston Texans","Las Vegas Raiders","5.5","+120","sports-illustrated");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Las Vegas Raiders","Houston Texans","-5.5","-143","sports-illustrated");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Houston Texans","Las Vegas Raiders","7","-110","sugarhouse");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Las Vegas Raiders","Houston Texans","-7","-110","sugarhouse");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Houston Texans","Las Vegas Raiders","7","-110","unibet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Las Vegas Raiders","Houston Texans","-7","-110","unibet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Atlanta Falcons","Cincinnati Bengals","10","-110","open-line");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Cincinnati Bengals","Atlanta Falcons","-10","-110","open-line");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Atlanta Falcons","Cincinnati Bengals","6.5","-109","vi-consensus");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Cincinnati Bengals","Atlanta Falcons","-6.5","-111","vi-consensus");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Atlanta Falcons","Cincinnati Bengals","6.5","-105","fanduel");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Cincinnati Bengals","Atlanta Falcons","-6.5","-115","fanduel");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Atlanta Falcons","Cincinnati Bengals","6.5","-110","playmgm");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Cincinnati Bengals","Atlanta Falcons","-6.5","-110","playmgm");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Atlanta Falcons","Cincinnati Bengals","6.5","-110","caesars-sportsbook");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Cincinnati Bengals","Atlanta Falcons","-6.5","-110","caesars-sportsbook");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Atlanta Falcons","Cincinnati Bengals","6.5","-105","wynnbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Cincinnati Bengals","Atlanta Falcons","-6.5","-115","wynnbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Atlanta Falcons","Cincinnati Bengals","6.5","-110","betrivers");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Cincinnati Bengals","Atlanta Falcons","-6.5","-110","betrivers");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Atlanta Falcons","Cincinnati Bengals","6.5","-105","pointsbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Cincinnati Bengals","Atlanta Falcons","-6.5","-110","pointsbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Atlanta Falcons","Cincinnati Bengals","7","-115","draftkings");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Cincinnati Bengals","Atlanta Falcons","-7","-105","draftkings");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Atlanta Falcons","Cincinnati Bengals","6.5","-110","sports-illustrated");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Cincinnati Bengals","Atlanta Falcons","-6.5","-110","sports-illustrated");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Atlanta Falcons","Cincinnati Bengals","6.5","-110","sugarhouse");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Cincinnati Bengals","Atlanta Falcons","-6.5","-110","sugarhouse");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Atlanta Falcons","Cincinnati Bengals","6.5","-110","unibet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Cincinnati Bengals","Atlanta Falcons","-6.5","-110","unibet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Detroit Lions","Dallas Cowboys","6.5","-110","open-line");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Dallas Cowboys","Detroit Lions","-6.5","-110","open-line");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Detroit Lions","Dallas Cowboys","7","-114","vi-consensus");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Dallas Cowboys","Detroit Lions","-7","-108","vi-consensus");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Detroit Lions","Dallas Cowboys","7","-115","fanduel");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Dallas Cowboys","Detroit Lions","-7","-105","fanduel");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Detroit Lions","Dallas Cowboys","7","-110","playmgm");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Dallas Cowboys","Detroit Lions","-7","-110","playmgm");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Detroit Lions","Dallas Cowboys","7","-110","caesars-sportsbook");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Dallas Cowboys","Detroit Lions","-7","-110","caesars-sportsbook");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Detroit Lions","Dallas Cowboys","6.5","-105","wynnbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Dallas Cowboys","Detroit Lions","-6.5","-115","wynnbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Detroit Lions","Dallas Cowboys","7","-114","betrivers");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Dallas Cowboys","Detroit Lions","-7","-108","betrivers");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Detroit Lions","Dallas Cowboys","7","-108","pointsbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Dallas Cowboys","Detroit Lions","-7","-108","pointsbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Detroit Lions","Dallas Cowboys","6.5","-105","draftkings");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Dallas Cowboys","Detroit Lions","-6.5","-115","draftkings");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Detroit Lions","Dallas Cowboys","5.5","+115","sports-illustrated");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Dallas Cowboys","Detroit Lions","-5.5","-139","sports-illustrated");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Detroit Lions","Dallas Cowboys","7","-114","sugarhouse");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Dallas Cowboys","Detroit Lions","-7","-108","sugarhouse");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Detroit Lions","Dallas Cowboys","7","-114","unibet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Dallas Cowboys","Detroit Lions","-7","-108","unibet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Indianapolis Colts","Tennessee Titans","1","-110","open-line");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Tennessee Titans","Indianapolis Colts","-1","-110","open-line");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Indianapolis Colts","Tennessee Titans","2.5","-109","vi-consensus");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Tennessee Titans","Indianapolis Colts","-2.5","-112","vi-consensus");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Indianapolis Colts","Tennessee Titans","2.5","-106","fanduel");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Tennessee Titans","Indianapolis Colts","-2.5","-114","fanduel");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Indianapolis Colts","Tennessee Titans","2.5","-110","playmgm");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Tennessee Titans","Indianapolis Colts","-2.5","-110","playmgm");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Indianapolis Colts","Tennessee Titans","2.5","-110","caesars-sportsbook");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Tennessee Titans","Indianapolis Colts","-2.5","-110","caesars-sportsbook");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Indianapolis Colts","Tennessee Titans","2.5","-105","wynnbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Tennessee Titans","Indianapolis Colts","-2.5","-115","wynnbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Indianapolis Colts","Tennessee Titans","2.5","-110","betrivers");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Tennessee Titans","Indianapolis Colts","-2.5","-110","betrivers");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Indianapolis Colts","Tennessee Titans","2.5","-105","pointsbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Tennessee Titans","Indianapolis Colts","-2.5","-110","pointsbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Indianapolis Colts","Tennessee Titans","2","-110","draftkings");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Tennessee Titans","Indianapolis Colts","-2","-110","draftkings");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Indianapolis Colts","Tennessee Titans","2.5","-110","sports-illustrated");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Tennessee Titans","Indianapolis Colts","-2.5","-110","sports-illustrated");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Indianapolis Colts","Tennessee Titans","2.5","-110","sugarhouse");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Tennessee Titans","Indianapolis Colts","-2.5","-110","sugarhouse");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Indianapolis Colts","Tennessee Titans","2.5","-110","unibet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Tennessee Titans","Indianapolis Colts","-2.5","-110","unibet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Green Bay Packers","Washington Commanders","-3","-110","open-line");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Washington Commanders","Green Bay Packers","3","-110","open-line");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Green Bay Packers","Washington Commanders","-4","-110","vi-consensus");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Washington Commanders","Green Bay Packers","4","-110","vi-consensus");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Green Bay Packers","Washington Commanders","-4.5","-104","fanduel");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Washington Commanders","Green Bay Packers","4.5","-118","fanduel");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Green Bay Packers","Washington Commanders","-4.5","-110","playmgm");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Washington Commanders","Green Bay Packers","4.5","-110","playmgm");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Green Bay Packers","Washington Commanders","-4","-110","caesars-sportsbook");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Washington Commanders","Green Bay Packers","4","-110","caesars-sportsbook");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Green Bay Packers","Washington Commanders","-4","-110","wynnbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Washington Commanders","Green Bay Packers","4","-110","wynnbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Green Bay Packers","Washington Commanders","-4","-110","betrivers");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Washington Commanders","Green Bay Packers","4","-110","betrivers");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Green Bay Packers","Washington Commanders","-4","-108","pointsbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Washington Commanders","Green Bay Packers","4","-108","pointsbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Green Bay Packers","Washington Commanders","-3.5","-110","draftkings");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Washington Commanders","Green Bay Packers","3.5","-110","draftkings");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Green Bay Packers","Washington Commanders","-4","-110","sports-illustrated");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Washington Commanders","Green Bay Packers","4","-110","sports-illustrated");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Green Bay Packers","Washington Commanders","-4","-110","sugarhouse");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Washington Commanders","Green Bay Packers","4","-110","sugarhouse");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Green Bay Packers","Washington Commanders","-4","-110","unibet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Washington Commanders","Green Bay Packers","4","-110","unibet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Tampa Bay Buccaneers","Carolina Panthers","-5","-110","open-line");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Carolina Panthers","Tampa Bay Buccaneers","5","-110","open-line");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Tampa Bay Buccaneers","Carolina Panthers","-13","-110","vi-consensus");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Carolina Panthers","Tampa Bay Buccaneers","13","-110","vi-consensus");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Tampa Bay Buccaneers","Carolina Panthers","-13.5","-105","fanduel");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Carolina Panthers","Tampa Bay Buccaneers","13.5","-115","fanduel");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Tampa Bay Buccaneers","Carolina Panthers","-13","-110","playmgm");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Carolina Panthers","Tampa Bay Buccaneers","13","-110","playmgm");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Tampa Bay Buccaneers","Carolina Panthers","-13","-110","caesars-sportsbook");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Carolina Panthers","Tampa Bay Buccaneers","13","-110","caesars-sportsbook");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Tampa Bay Buccaneers","Carolina Panthers","-13","-110","wynnbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Carolina Panthers","Tampa Bay Buccaneers","13","-110","wynnbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Tampa Bay Buccaneers","Carolina Panthers","-13","-110","betrivers");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Carolina Panthers","Tampa Bay Buccaneers","13","-110","betrivers");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Tampa Bay Buccaneers","Carolina Panthers","-12.5","-108","pointsbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Carolina Panthers","Tampa Bay Buccaneers","12.5","-108","pointsbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Tampa Bay Buccaneers","Carolina Panthers","-13.5","-110","draftkings");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Carolina Panthers","Tampa Bay Buccaneers","13.5","-110","draftkings");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Tampa Bay Buccaneers","Carolina Panthers","-11.5","-125","sports-illustrated");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Carolina Panthers","Tampa Bay Buccaneers","11.5","+105","sports-illustrated");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Tampa Bay Buccaneers","Carolina Panthers","-13","-110","sugarhouse");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Carolina Panthers","Tampa Bay Buccaneers","13","-110","sugarhouse");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Tampa Bay Buccaneers","Carolina Panthers","-13","-110","unibet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Carolina Panthers","Tampa Bay Buccaneers","13","-110","unibet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New York Giants","Jacksonville Jaguars","1.5","-110","open-line");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Jacksonville Jaguars","New York Giants","-1.5","-110","open-line");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New York Giants","Jacksonville Jaguars","3","-106","vi-consensus");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Jacksonville Jaguars","New York Giants","-3","-115","vi-consensus");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New York Giants","Jacksonville Jaguars","3","-104","fanduel");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Jacksonville Jaguars","New York Giants","-3","-118","fanduel");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New York Giants","Jacksonville Jaguars","3","-105","playmgm");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Jacksonville Jaguars","New York Giants","-3","-115","playmgm");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New York Giants","Jacksonville Jaguars","3","-105","caesars-sportsbook");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Jacksonville Jaguars","New York Giants","-3","-115","caesars-sportsbook");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New York Giants","Jacksonville Jaguars","3","-105","wynnbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Jacksonville Jaguars","New York Giants","-3","-115","wynnbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New York Giants","Jacksonville Jaguars","3","-106","betrivers");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Jacksonville Jaguars","New York Giants","-3","-114","betrivers");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New York Giants","Jacksonville Jaguars","3.5","-108","pointsbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Jacksonville Jaguars","New York Giants","-3.5","-108","pointsbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New York Giants","Jacksonville Jaguars","3","-105","draftkings");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Jacksonville Jaguars","New York Giants","-3","-115","draftkings");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New York Giants","Jacksonville Jaguars","4.5","-139","sports-illustrated");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Jacksonville Jaguars","New York Giants","-4.5","+115","sports-illustrated");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New York Giants","Jacksonville Jaguars","3","-106","sugarhouse");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Jacksonville Jaguars","New York Giants","-3","-114","sugarhouse");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New York Giants","Jacksonville Jaguars","3","-106","unibet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Jacksonville Jaguars","New York Giants","-3","-114","unibet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Cleveland Browns","Baltimore Ravens","5","-110","open-line");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Baltimore Ravens","Cleveland Browns","-5","-110","open-line");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Cleveland Browns","Baltimore Ravens","6.5","-110","vi-consensus");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Baltimore Ravens","Cleveland Browns","-6.5","-111","vi-consensus");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Cleveland Browns","Baltimore Ravens","6.5","-105","fanduel");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Baltimore Ravens","Cleveland Browns","-6.5","-115","fanduel");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Cleveland Browns","Baltimore Ravens","6.5","-110","playmgm");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Baltimore Ravens","Cleveland Browns","-6.5","-110","playmgm");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Cleveland Browns","Baltimore Ravens","6.5","-110","caesars-sportsbook");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Baltimore Ravens","Cleveland Browns","-6.5","-110","caesars-sportsbook");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Cleveland Browns","Baltimore Ravens","6.5","-110","wynnbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Baltimore Ravens","Cleveland Browns","-6.5","-110","wynnbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Cleveland Browns","Baltimore Ravens","6.5","-110","betrivers");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Baltimore Ravens","Cleveland Browns","-6.5","-110","betrivers");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Cleveland Browns","Baltimore Ravens","6.5","+100","pointsbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Baltimore Ravens","Cleveland Browns","-6.5","-115","pointsbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Cleveland Browns","Baltimore Ravens","6.5","-105","draftkings");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Baltimore Ravens","Cleveland Browns","-6.5","-115","draftkings");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Cleveland Browns","Baltimore Ravens","6.5","-110","sports-illustrated");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Baltimore Ravens","Cleveland Browns","-6.5","-110","sports-illustrated");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Cleveland Browns","Baltimore Ravens","6.5","-110","sugarhouse");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Baltimore Ravens","Cleveland Browns","-6.5","-110","sugarhouse");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Cleveland Browns","Baltimore Ravens","6.5","-110","unibet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Baltimore Ravens","Cleveland Browns","-6.5","-110","unibet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New Orleans Saints","Arizona Cardinals","3","-110","open-line");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Arizona Cardinals","New Orleans Saints","-3","-110","open-line");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New Orleans Saints","Arizona Cardinals","2.5","-109","vi-consensus");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Arizona Cardinals","New Orleans Saints","-2.5","-112","vi-consensus");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New Orleans Saints","Arizona Cardinals","2.5","-110","fanduel");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Arizona Cardinals","New Orleans Saints","-2.5","-110","fanduel");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New Orleans Saints","Arizona Cardinals","2.5","-110","playmgm");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Arizona Cardinals","New Orleans Saints","-2.5","-110","playmgm");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New Orleans Saints","Arizona Cardinals","2.5","-110","caesars-sportsbook");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Arizona Cardinals","New Orleans Saints","-2.5","-110","caesars-sportsbook");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New Orleans Saints","Arizona Cardinals","2.5","-105","wynnbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Arizona Cardinals","New Orleans Saints","-2.5","-115","wynnbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New Orleans Saints","Arizona Cardinals","2.5","-109","betrivers");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Arizona Cardinals","New Orleans Saints","-2.5","-112","betrivers");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New Orleans Saints","Arizona Cardinals","2.5","-105","pointsbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Arizona Cardinals","New Orleans Saints","-2.5","-110","pointsbet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New Orleans Saints","Arizona Cardinals","2.5","-105","draftkings");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Arizona Cardinals","New Orleans Saints","-2.5","-115","draftkings");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New Orleans Saints","Arizona Cardinals","2.5","-110","sports-illustrated");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Arizona Cardinals","New Orleans Saints","-2.5","-110","sports-illustrated");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New Orleans Saints","Arizona Cardinals","2.5","-109","sugarhouse");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Arizona Cardinals","New Orleans Saints","-2.5","-112","sugarhouse");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","New Orleans Saints","Arizona Cardinals","2.5","-109","unibet");
INSERT INTO `SPREAD` (`week`,`team`,`opponent`,`spread`,`odds`,`bookmaker`) VALUES ("7","Arizona Cardinals","New Orleans Saints","-2.5","-112","unibet");
